default: &default
adapter: postgresql
encoding: unicode
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: incubit_assessment_development

test:
  <<: *default
  database: incubit_assessment_test

production:
  <<: *default
  database: 
  username: 
  password: <%= ENV['INCUBIT_ASSESSMENT_DATABASE_PASSWORD'] %>
